spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msa
    username: msa
    password: '{cipher}028c3e52229f3eb4bc62fcbc923a89cf973d4619a36e3030e2a1c15b5a751115'

token:
  expiration_time: 86400000
  secret: user_token_native_user_service_default

gateway:
  ip: 192.168.0.14